[kube_main]
kube_main_01 ansible_host=192.168.10.103 ansible_user=victor ansible_port=2816 ansible_ssh_private_key_file=~/.ssh/id_homelab

[kube_workers]
kube_worker_dns_01 ansible_host=192.168.10.2 ansible_user=victor ansible_port=2816 ansible_ssh_private_key_file=~/.ssh/id_homelab
kube_worker_db_01 ansible_host=192.168.10.105 ansible_user=victor ansible_port=2816 ansible_ssh_private_key_file=~/.ssh/id_homelab

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'